name = "通用人工智能实验班"
license = "MIT"
licenselink = "https://github.com/wowchemy/starter-hugo-research-group/blob/main/LICENSE.md"
description = "清华大学、北京大学通用人工智能实验班官方网站。"
homepage = "https://github.com/wowchemy/starter-hugo-research-group"
demosite = "https://research-group.netlify.app/"
tags = ["academic",
        "university",
        "research",
        "publications",
        "widgets",
        "portfolio",
        "responsive",
        "clean",
        "company",
        "blog",
        "events",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "landing page",
        "contact form",
        "mobile",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "slide",
        "AI"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "Yuyang Li"
  homepage = "https://yuyangli.com"
